stages:
  - setup
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

setup:
  stage: setup
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  before_script:
    - apk add --no-cache curl bash make docker 
  script:
    - docker --version

test:
  stage: test
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  before_script:
    - apk add --no-cache curl bash make docker-compose
  script:
    - docker compose up --build -d 
    - sleep 10 
  after_script:
    - docker compose down 